### ISSUE TITLE
Malformed url entry causes cascading errors

### ISSUE THREAD

**Issue by Derek-Jones** [dspinellis/bib2xhtml#11]
The following bibtex entry:

@Article{Ferens_98,
  author =       "Daniel V. Ferens and David S. Christensen",
 url = "https://google.com/search?q=%22Calibrating+Software+Cost+Models+to+{Department%22+filetype:pdf",
  title =        "Calibrating Software Cost Models to {Department
	 of Defense} Databases\textendash {A} Review of Ten Studies",
  journal =      "ISPA Journal of Parametrics",
  volume =       "XVIII",
  number =       "2",
  pages =        "55--74",
  month =        nov,
  year =         "1998",
  online =       "CalibratingSWCostModel.pdf",
}

causes the error "Illegal end of database file".
With a longer bibtex file the message is:
"Your field is more than 20000 characters"

The problem is cause by the line: {Department%22+filetype:pdf",
missing a closing "}".

The url line was automatically generated from the title line (and, yes I should fit it to handle multiple line titles).

**Comment by Derek-Jones** [comment]
My understanding is that google ignores all non-ascii characters in search string.

There might be a bibtext requirement.  I will check.  I could simply strip out any { or }.

I reported this problem because it took me a long time to track down what was causing the behavior.

**Comment by dspinellis** [comment]
It is indeed a BibTeX requirement.
