### ISSUE TITLE
Author sorting needs to use more name information

### ISSUE THREAD

**Issue by Derek-Jones** [dspinellis/bib2xhtml#14]
Generated output for Dave Jones and Derek Jones are intermixed, when in date sorted order (the default behavior).  More author name characters need to be be used in the sort process.

There is no sort routine easily visible to somebody with little knowledge of the arcania of Perl.

**Comment by dspinellis** [comment]
I can't see any sorting in the Perl code.  Sorting is implemented in BibTeX, whose style language is even more arcane then Perl's.

**Comment by Derek-Jones** [comment]
Oh, yes.

I am using xabbrev as the bst file,  so the bibitem labels are not designed for correct author sorting.
