### ISSUE TITLE
ring uU supported in html+ three unsupported accents

### ISSUE THREAD

**Issue by Derek-Jones** [dspinellis/bib2xhtml#15]
The ring characters \r{u} and \r{U} have html support

Around line 304

        s/\\r(\001\d+)\{U\1\}/&#366;/g;
        s/\\r(\001\d+)\{u\1\}/&#367;/g;

        # The following accents have no HTML equivalent.
        # (This list is still not complete.)
        s/\\b(\001\d+)\{(.)\1\}/$2/gs;                  # accent \b{x}
        s/\\d(\001\d+)\{(.)\1\}/$2/gs;                  # accent \d{x}
        s/\\H(\001\d+)\{(.)\1\}/$2/gs;                  # accent \H{x}
        s/\\r(\001\d+)\{(.)\1\}/$2/gs;                   # ring accent \r{x}

Also, the following after the pounds mapping, around line 326

	s/\\pm\b\s*/&plusmn;/g;;                        # \pm -> &plusmn;

**Comment by dspinellis** [comment]
Thank you for the \pm suggestion.  As far as I understand, `&#366;` and `367` are references to Universal Character Set/Unicode code points.  (See e.g. [here](http://www.codetable.net/decimal/366).) If we go down that road we can drop the conversion to HTML named entities. Instead we can convert everything to Unicode and write out the Unicode code points using the `&#nnn` format.  Right?

**Comment by Derek-Jones** [comment]
My interest in \r{u} is driven by a [bibtext file](http://www.knosof.co.uk/ESEUR/ESEUR-references.html) containing them.

A quick search on html portability "named entity" unicode
found a few pages from 2010 and before talking about portability issues.  Nothing that serious.

Named entities make ti easier to read the html (does anybody other than us do that?)

A single conversion routine would make your maintenance life easier (rather than utf+html).

You're the guy at the sharp end.  The rest of us follow :-)

**Comment by dspinellis** [comment]
Good point regarding named entities.
