### ISSUE TITLE
utf8 issues on Windows

### ISSUE THREAD

**Issue by auge** [dspinellis/bib2xhtml#18]
I already have utf8 characters in the bib file, which are not preserved when parsing through bib2xhtml

the dummy bib-file
```
@InProceedings{first2018a,
  author    = {Firstć Lastž and Second Thirdü},
  title     = {Just my title},
  booktitle = {Pattern Recognition},
  year      = {2018},
  timestamp = {2018-07-10},
}
```
It looks like the characters (ćžü) are "doubly encoded"

The call:
```
perl bib2xhtml.pl -u dummy.bib
```
produces some nasty characters

I can workaround it by removing the "use utf8" and "binmode(HTMLFILE, ":encoding(UTF-8)") if ($opt_u);" statement from the bib2xhtml.pl-script.

**Comment by auge** [comment]
using mingw64 (git 4 windows) on windows10-x64

**Comment by auge** [comment]
[dummy.bib.log](https://github.com/dspinellis/bib2xhtml/files/2733285/dummy.bib.log)

**Comment by dspinellis** [comment]
I think you'd need to add support for a new -U option to decode UTF-8 appearing in the input file.  Would you like to try implementing it?

**Comment by auge** [comment]
that should be rather simple (just set the input mode to binary - like for the output) ??
I can try

**Comment by auge** [comment]
ok, I have something working here ... I'll post it tomorrow

**Comment by dspinellis** [comment]
Excellent!  Please also update the documentation, and if possible, the tests.
