### ISSUE TITLE
problem with https doi links

### ISSUE THREAD

**Issue by sbecuwe** [dspinellis/bib2xhtml#21]
Hello

Following line in a bib file `doi={https://doi.org/...}` leads to `[<a href="http://dx.doi.org/https://doi.org/...] ` in the output file, so writing `https://` seems to be problematic. I think it's sufficient to replace line 247 by `($url =~ m/^http(s?):\/\/[\w.]+\/(.*)/i) ||` to fix the problem.

Regards, Stefan

**Comment by auge** [comment]
the proper way to enter doi entries is to write only the number there. else it would be a url.

so simply fix your bib file:
doi={TED.2019....},

KR, Benjamin

**Comment by dspinellis** [comment]
I agree with @auege.  I checked, and the BibTeX records exported by IEEE Xplore, the ACM DL, and DBLP are all consistent with what @auege recommends.
