### ISSUE TITLE
couldn't open style file - example.bib on Mac El Capitan

### ISSUE THREAD

**Issue by paynito** [dspinellis/bib2xhtml#4]
bib2xhtml git:(master) ✗ perl bib2xhtml.pl example.bib
<?xml version="1.0" encoding="US-ASCII"?>
<!DOCTYPE html
	PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Bibliography generated from example.bib</title>
<meta http-equiv="Content-type" content="text/html; charset=US-ASCII" />
<meta name="Generator" content="$Id: \dds\src\textproc\bib2xhtml\RCS\bib2xhtml,v 2.38 2011/10/19 15:15:05 dds Exp $" />
</head>
<body>
This is BibTeX, Version 0.99d (TeX Live 2015)
The top-level auxiliary file: bib14320.aux
I couldn't open style file html-n.bst
---line 3 of file bib14320.aux
 : \bibstyle{html-n
 :                 }
I'm skipping whatever remains of this command
I found no style file---while reading file bib14320.aux
(There were 2 error messages)

<ul class="bib2xhtml">

</ul>

</body></html>

**Comment by auge** [comment]
first you have to run gen-bst.pl, then you can use the bib2xhtml.pl script

**Comment by paynito** [comment]
Thank you.  MWE:
After cloning the repository cd into it.
You should have LaTeX and Perl installed on your computer.
at the prompt type
perl gen-bst.pl example.bib
then
perl bib2xhtml.pl example.bib
you now see the output html in your terminal
now try with your own file, add it to the same folder
then
perl bib2xhtml.pl my.bib
note that you did not have to re-run gen-bst.pl
