### ISSUE TITLE
bib2xhtml produces dos-style line endings

### ISSUE THREAD

**Issue by gdevenyi** [dspinellis/bib2xhtml#7]
For some reason the resulting HTML lines produced by bib2xhtml have DOS-style line endings rather than UNIX line endings.

I always fix this after with dos2unix.

**Comment by dspinellis** [comment]
Under which OS and version of Perl does that happen?  On native Windows this is the expected behaviour. It can be changed by toying with `binmode` and `open` arguments, but I don't think it's the correct thing to do. In Rome do as Romans do.

**Comment by gdevenyi** [comment]
Ubuntu 14.04.3,
```
$ perl --version

This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-gnu-thread-multi
(with 44 registered patches, see perl -V for more detail)

Copyright 1987-2013, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

```

**Comment by dspinellis** [comment]
Then it's a bug.

**Comment by gdevenyi** [comment]
My reading of https://github.com/dspinellis/bib2xhtml/blob/master/bib2xhtml.pl#L28
Is it is intentionally creating windows line endings, based on http://perldoc.perl.org/PerlIO.html

**Comment by gdevenyi** [comment]
> On write converts each "\n" to a CR,LF pair. Note that this layer will silently refuse to be pushed on top of itself.

**Comment by dspinellis** [comment]
Hmm.  It was introduced for a reason; see 02f8b2b3.  Maybe it's no longer needed.

**Comment by gdevenyi** [comment]
Well, removing it on Linux at least fixes my issue.

**Comment by gdevenyi** [comment]
Looks to me like a broken perl on windows. I don't have a windows setup to test though. Seems as though there should be some system OS check that could wrap that setting.

**Comment by dspinellis** [comment]
What did you change `use open` to?  We'd like it to use the native convention.

**Comment by gdevenyi** [comment]
I just commented out the line.

**Comment by dspinellis** [comment]
Commenting out the line fails to read `example.bib` (generates no bibliography entries) on
```
$ perl --version

This is perl 5, version 22, subversion 2 (v5.22.2) built for cygwin-thread-multi-64int
```

**Comment by gdevenyi** [comment]
okay, so it looks like if you use something like this:
https://stackoverflow.com/questions/334686/how-can-i-detect-the-operating-system-in-perl

to wrap the option for read/write code that might work?

**Comment by dspinellis** [comment]
I'd prefer to understand the issue and adjust the code to handle it robustly, rather than fix the symptom according to the OS.

**Comment by gdevenyi** [comment]
Reply #1 here http://www.perlmonks.org/?node_id=961294 notes that it's just inconsistent on differnt windows perl versions...

Looks like we're just supposed to use "\n" and perl should handle it.

**Comment by gdevenyi** [comment]
Switching the line to:
``use open IN => ':crlf';`` also works, does that work on cygwin?

**Comment by gdevenyi** [comment]
I should also note, ``make test`` fails on Linux with the current code (probably due to the line endings)

**Comment by dspinellis** [comment]
* I pushed a change that should allow test to ignore line ending differences.
* Strangely, `use open IN => ':crlf';` still produces an empty bibliography.

**Comment by dspinellis** [comment]
I found the problem.  The use of `$/` to read blank-line-separated blocks, fails to work correctly with `open IN` when CR-LF line endings are used.  

# Works
```
use open IO => ':crlf';

$/ = '';
open(my $in, "<", "a") || die;
while (<$in>) {
	print "[$_]\n";
}
```

# Does not work
```
use open IN => ':crlf';

$/ = '';
open(my $in, "<", "a") || die;
while (<$in>) {
	print "[$_]\n";
}
```

# Works
```
$/ = '';
open(my $in, "<:crlf", "a") || die;
while (<$in>) {
	print "[$_]\n";
}
```

**Comment by gdevenyi** [comment]
Wonderful, ``make test`` now passes on Linux and I get native line endings! Thanks for the great tool!

**Comment by dspinellis** [comment]
:+1:
